Search.appendIndex(
    [
                {
            "fqsen": "\\App\\Controller\\ApprovalOrdersController",
            "name": "ApprovalOrdersController",
            "summary": "Controller\u0020\u0020as\u0020stub\u0020route\u0020for\u0020order\u0020approval.",
            "url": "classes/App-Controller-ApprovalOrdersController.html"
        },                {
            "fqsen": "\\App\\Controller\\ApprovalOrdersController\u003A\u003Aapprove\u0028\u0029",
            "name": "approve",
            "summary": "Request\u0020Stub\u0020GET\u0020\u003A\u0020\/approve",
            "url": "classes/App-Controller-ApprovalOrdersController.html#method_approve"
        },                {
            "fqsen": "\\App\\Controller\\ReservationOrderController",
            "name": "ReservationOrderController",
            "summary": "Controller\u0020\u0020as\u0020stub\u0020route\u0020for\u0020order\u0020reservation.",
            "url": "classes/App-Controller-ReservationOrderController.html"
        },                {
            "fqsen": "\\App\\Controller\\ReservationOrderController\u003A\u003Anew\u0028\u0029",
            "name": "new",
            "summary": "Request\u0020Stub\u0020GET\u0020\u003A\u0020\/book",
            "url": "classes/App-Controller-ReservationOrderController.html#method_new"
        },                {
            "fqsen": "\\App\\Controller\\TicketOrderController",
            "name": "TicketOrderController",
            "summary": "Manages\u0020the\u0020order\u0020for\u0020tickets",
            "url": "classes/App-Controller-TicketOrderController.html"
        },                {
            "fqsen": "\\App\\Controller\\TicketOrderController\u003A\u003Anew\u0028\u0029",
            "name": "new",
            "summary": "Creates\u0020a\u0020new\u0020order\u0020for\u0020an\u0020event.",
            "url": "classes/App-Controller-TicketOrderController.html#method_new"
        },                {
            "fqsen": "\\App\\Controller\\ValidateRequestTrait",
            "name": "ValidateRequestTrait",
            "summary": "Validation\u0020helper\u0020methods",
            "url": "classes/App-Controller-ValidateRequestTrait.html"
        },                {
            "fqsen": "\\App\\Controller\\ValidateRequestTrait\u003A\u003AcheckRequestKeys\u0028\u0029",
            "name": "checkRequestKeys",
            "summary": "Checks\u0020the\u0020presence\u0020of\u0020the\u0020required\u0020parameters",
            "url": "classes/App-Controller-ValidateRequestTrait.html#method_checkRequestKeys"
        },                {
            "fqsen": "\\App\\Entity\\BarcodeMemory",
            "name": "BarcodeMemory",
            "summary": "The\u0020entity\u0020of\u0020the\u0020barcodes\u0020buffer",
            "url": "classes/App-Entity-BarcodeMemory.html"
        },                {
            "fqsen": "\\App\\Entity\\BarcodeMemory\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/App-Entity-BarcodeMemory.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\BarcodeMemory\u003A\u003AgetBarcode\u0028\u0029",
            "name": "getBarcode",
            "summary": "",
            "url": "classes/App-Entity-BarcodeMemory.html#method_getBarcode"
        },                {
            "fqsen": "\\App\\Entity\\BarcodeMemory\u003A\u003AsetBarcode\u0028\u0029",
            "name": "setBarcode",
            "summary": "",
            "url": "classes/App-Entity-BarcodeMemory.html#method_setBarcode"
        },                {
            "fqsen": "\\App\\Entity\\BarcodeMemory\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Entity-BarcodeMemory.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\BarcodeMemory\u003A\u003A\u0024barcode",
            "name": "barcode",
            "summary": "",
            "url": "classes/App-Entity-BarcodeMemory.html#property_barcode"
        },                {
            "fqsen": "\\App\\Entity\\TicketOrder",
            "name": "TicketOrder",
            "summary": "",
            "url": "classes/App-Entity-TicketOrder.html"
        },                {
            "fqsen": "\\App\\Entity\\TicketOrder\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/App-Entity-TicketOrder.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\TicketOrder\u003A\u003AgetEventId\u0028\u0029",
            "name": "getEventId",
            "summary": "",
            "url": "classes/App-Entity-TicketOrder.html#method_getEventId"
        },                {
            "fqsen": "\\App\\Entity\\TicketOrder\u003A\u003AsetEventId\u0028\u0029",
            "name": "setEventId",
            "summary": "",
            "url": "classes/App-Entity-TicketOrder.html#method_setEventId"
        },                {
            "fqsen": "\\App\\Entity\\TicketOrder\u003A\u003AgetEventDate\u0028\u0029",
            "name": "getEventDate",
            "summary": "",
            "url": "classes/App-Entity-TicketOrder.html#method_getEventDate"
        },                {
            "fqsen": "\\App\\Entity\\TicketOrder\u003A\u003AsetEventDate\u0028\u0029",
            "name": "setEventDate",
            "summary": "",
            "url": "classes/App-Entity-TicketOrder.html#method_setEventDate"
        },                {
            "fqsen": "\\App\\Entity\\TicketOrder\u003A\u003AgetTicketAdultPrice\u0028\u0029",
            "name": "getTicketAdultPrice",
            "summary": "",
            "url": "classes/App-Entity-TicketOrder.html#method_getTicketAdultPrice"
        },                {
            "fqsen": "\\App\\Entity\\TicketOrder\u003A\u003AsetTicketAdultPrice\u0028\u0029",
            "name": "setTicketAdultPrice",
            "summary": "",
            "url": "classes/App-Entity-TicketOrder.html#method_setTicketAdultPrice"
        },                {
            "fqsen": "\\App\\Entity\\TicketOrder\u003A\u003AgetTicketAdultQuantity\u0028\u0029",
            "name": "getTicketAdultQuantity",
            "summary": "",
            "url": "classes/App-Entity-TicketOrder.html#method_getTicketAdultQuantity"
        },                {
            "fqsen": "\\App\\Entity\\TicketOrder\u003A\u003AsetTicketAdultQuantity\u0028\u0029",
            "name": "setTicketAdultQuantity",
            "summary": "",
            "url": "classes/App-Entity-TicketOrder.html#method_setTicketAdultQuantity"
        },                {
            "fqsen": "\\App\\Entity\\TicketOrder\u003A\u003AgetTicketKidPrice\u0028\u0029",
            "name": "getTicketKidPrice",
            "summary": "",
            "url": "classes/App-Entity-TicketOrder.html#method_getTicketKidPrice"
        },                {
            "fqsen": "\\App\\Entity\\TicketOrder\u003A\u003AsetTicketKidPrice\u0028\u0029",
            "name": "setTicketKidPrice",
            "summary": "",
            "url": "classes/App-Entity-TicketOrder.html#method_setTicketKidPrice"
        },                {
            "fqsen": "\\App\\Entity\\TicketOrder\u003A\u003AgetTicketKidQuantity\u0028\u0029",
            "name": "getTicketKidQuantity",
            "summary": "",
            "url": "classes/App-Entity-TicketOrder.html#method_getTicketKidQuantity"
        },                {
            "fqsen": "\\App\\Entity\\TicketOrder\u003A\u003AsetTicketKidQuantity\u0028\u0029",
            "name": "setTicketKidQuantity",
            "summary": "",
            "url": "classes/App-Entity-TicketOrder.html#method_setTicketKidQuantity"
        },                {
            "fqsen": "\\App\\Entity\\TicketOrder\u003A\u003AgetBarcode\u0028\u0029",
            "name": "getBarcode",
            "summary": "",
            "url": "classes/App-Entity-TicketOrder.html#method_getBarcode"
        },                {
            "fqsen": "\\App\\Entity\\TicketOrder\u003A\u003AsetBarcode\u0028\u0029",
            "name": "setBarcode",
            "summary": "",
            "url": "classes/App-Entity-TicketOrder.html#method_setBarcode"
        },                {
            "fqsen": "\\App\\Entity\\TicketOrder\u003A\u003AgetEqualPrice\u0028\u0029",
            "name": "getEqualPrice",
            "summary": "",
            "url": "classes/App-Entity-TicketOrder.html#method_getEqualPrice"
        },                {
            "fqsen": "\\App\\Entity\\TicketOrder\u003A\u003AsetEqualPrice\u0028\u0029",
            "name": "setEqualPrice",
            "summary": "",
            "url": "classes/App-Entity-TicketOrder.html#method_setEqualPrice"
        },                {
            "fqsen": "\\App\\Entity\\TicketOrder\u003A\u003AgetCreated\u0028\u0029",
            "name": "getCreated",
            "summary": "",
            "url": "classes/App-Entity-TicketOrder.html#method_getCreated"
        },                {
            "fqsen": "\\App\\Entity\\TicketOrder\u003A\u003AsetCreated\u0028\u0029",
            "name": "setCreated",
            "summary": "",
            "url": "classes/App-Entity-TicketOrder.html#method_setCreated"
        },                {
            "fqsen": "\\App\\Entity\\TicketOrder\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Entity-TicketOrder.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\TicketOrder\u003A\u003A\u0024event_id",
            "name": "event_id",
            "summary": "",
            "url": "classes/App-Entity-TicketOrder.html#property_event_id"
        },                {
            "fqsen": "\\App\\Entity\\TicketOrder\u003A\u003A\u0024event_date",
            "name": "event_date",
            "summary": "",
            "url": "classes/App-Entity-TicketOrder.html#property_event_date"
        },                {
            "fqsen": "\\App\\Entity\\TicketOrder\u003A\u003A\u0024ticket_adult_price",
            "name": "ticket_adult_price",
            "summary": "",
            "url": "classes/App-Entity-TicketOrder.html#property_ticket_adult_price"
        },                {
            "fqsen": "\\App\\Entity\\TicketOrder\u003A\u003A\u0024ticket_adult_quantity",
            "name": "ticket_adult_quantity",
            "summary": "",
            "url": "classes/App-Entity-TicketOrder.html#property_ticket_adult_quantity"
        },                {
            "fqsen": "\\App\\Entity\\TicketOrder\u003A\u003A\u0024ticket_kid_price",
            "name": "ticket_kid_price",
            "summary": "",
            "url": "classes/App-Entity-TicketOrder.html#property_ticket_kid_price"
        },                {
            "fqsen": "\\App\\Entity\\TicketOrder\u003A\u003A\u0024ticket_kid_quantity",
            "name": "ticket_kid_quantity",
            "summary": "",
            "url": "classes/App-Entity-TicketOrder.html#property_ticket_kid_quantity"
        },                {
            "fqsen": "\\App\\Entity\\TicketOrder\u003A\u003A\u0024barcode",
            "name": "barcode",
            "summary": "",
            "url": "classes/App-Entity-TicketOrder.html#property_barcode"
        },                {
            "fqsen": "\\App\\Entity\\TicketOrder\u003A\u003A\u0024equal_price",
            "name": "equal_price",
            "summary": "",
            "url": "classes/App-Entity-TicketOrder.html#property_equal_price"
        },                {
            "fqsen": "\\App\\Entity\\TicketOrder\u003A\u003A\u0024created",
            "name": "created",
            "summary": "",
            "url": "classes/App-Entity-TicketOrder.html#property_created"
        },                {
            "fqsen": "\\App\\Entity\\TicketOrderInterface",
            "name": "TicketOrderInterface",
            "summary": "The\u0020entity\u0020of\u0020the\u0020ticket\u0020\u0020orders\u0020\u0020stack",
            "url": "classes/App-Entity-TicketOrderInterface.html"
        },                {
            "fqsen": "\\App\\Entity\\TicketOrderInterface\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/App-Entity-TicketOrderInterface.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\TicketOrderInterface\u003A\u003AgetEventId\u0028\u0029",
            "name": "getEventId",
            "summary": "",
            "url": "classes/App-Entity-TicketOrderInterface.html#method_getEventId"
        },                {
            "fqsen": "\\App\\Entity\\TicketOrderInterface\u003A\u003AsetEventId\u0028\u0029",
            "name": "setEventId",
            "summary": "",
            "url": "classes/App-Entity-TicketOrderInterface.html#method_setEventId"
        },                {
            "fqsen": "\\App\\Entity\\TicketOrderInterface\u003A\u003AgetEventDate\u0028\u0029",
            "name": "getEventDate",
            "summary": "",
            "url": "classes/App-Entity-TicketOrderInterface.html#method_getEventDate"
        },                {
            "fqsen": "\\App\\Entity\\TicketOrderInterface\u003A\u003AsetEventDate\u0028\u0029",
            "name": "setEventDate",
            "summary": "",
            "url": "classes/App-Entity-TicketOrderInterface.html#method_setEventDate"
        },                {
            "fqsen": "\\App\\Entity\\TicketOrderInterface\u003A\u003AgetTicketAdultPrice\u0028\u0029",
            "name": "getTicketAdultPrice",
            "summary": "",
            "url": "classes/App-Entity-TicketOrderInterface.html#method_getTicketAdultPrice"
        },                {
            "fqsen": "\\App\\Entity\\TicketOrderInterface\u003A\u003AsetTicketAdultPrice\u0028\u0029",
            "name": "setTicketAdultPrice",
            "summary": "",
            "url": "classes/App-Entity-TicketOrderInterface.html#method_setTicketAdultPrice"
        },                {
            "fqsen": "\\App\\Entity\\TicketOrderInterface\u003A\u003AgetTicketAdultQuantity\u0028\u0029",
            "name": "getTicketAdultQuantity",
            "summary": "",
            "url": "classes/App-Entity-TicketOrderInterface.html#method_getTicketAdultQuantity"
        },                {
            "fqsen": "\\App\\Entity\\TicketOrderInterface\u003A\u003AsetTicketAdultQuantity\u0028\u0029",
            "name": "setTicketAdultQuantity",
            "summary": "",
            "url": "classes/App-Entity-TicketOrderInterface.html#method_setTicketAdultQuantity"
        },                {
            "fqsen": "\\App\\Entity\\TicketOrderInterface\u003A\u003AgetTicketKidPrice\u0028\u0029",
            "name": "getTicketKidPrice",
            "summary": "",
            "url": "classes/App-Entity-TicketOrderInterface.html#method_getTicketKidPrice"
        },                {
            "fqsen": "\\App\\Entity\\TicketOrderInterface\u003A\u003AsetTicketKidPrice\u0028\u0029",
            "name": "setTicketKidPrice",
            "summary": "",
            "url": "classes/App-Entity-TicketOrderInterface.html#method_setTicketKidPrice"
        },                {
            "fqsen": "\\App\\Entity\\TicketOrderInterface\u003A\u003AgetTicketKidQuantity\u0028\u0029",
            "name": "getTicketKidQuantity",
            "summary": "",
            "url": "classes/App-Entity-TicketOrderInterface.html#method_getTicketKidQuantity"
        },                {
            "fqsen": "\\App\\Entity\\TicketOrderInterface\u003A\u003AsetTicketKidQuantity\u0028\u0029",
            "name": "setTicketKidQuantity",
            "summary": "",
            "url": "classes/App-Entity-TicketOrderInterface.html#method_setTicketKidQuantity"
        },                {
            "fqsen": "\\App\\Entity\\TicketOrderInterface\u003A\u003AgetBarcode\u0028\u0029",
            "name": "getBarcode",
            "summary": "",
            "url": "classes/App-Entity-TicketOrderInterface.html#method_getBarcode"
        },                {
            "fqsen": "\\App\\Entity\\TicketOrderInterface\u003A\u003AsetBarcode\u0028\u0029",
            "name": "setBarcode",
            "summary": "",
            "url": "classes/App-Entity-TicketOrderInterface.html#method_setBarcode"
        },                {
            "fqsen": "\\App\\Entity\\TicketOrderInterface\u003A\u003AgetEqualPrice\u0028\u0029",
            "name": "getEqualPrice",
            "summary": "",
            "url": "classes/App-Entity-TicketOrderInterface.html#method_getEqualPrice"
        },                {
            "fqsen": "\\App\\Entity\\TicketOrderInterface\u003A\u003AsetEqualPrice\u0028\u0029",
            "name": "setEqualPrice",
            "summary": "",
            "url": "classes/App-Entity-TicketOrderInterface.html#method_setEqualPrice"
        },                {
            "fqsen": "\\App\\Entity\\TicketOrderInterface\u003A\u003AgetCreated\u0028\u0029",
            "name": "getCreated",
            "summary": "",
            "url": "classes/App-Entity-TicketOrderInterface.html#method_getCreated"
        },                {
            "fqsen": "\\App\\Entity\\TicketOrderInterface\u003A\u003AsetCreated\u0028\u0029",
            "name": "setCreated",
            "summary": "",
            "url": "classes/App-Entity-TicketOrderInterface.html#method_setCreated"
        },                {
            "fqsen": "\\App\\EntryLocal\\ServiceResponse",
            "name": "ServiceResponse",
            "summary": "Successful\u0020response\u0020properties\u0020class",
            "url": "classes/App-EntryLocal-ServiceResponse.html"
        },                {
            "fqsen": "\\App\\EntryLocal\\ServiceResponse\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-EntryLocal-ServiceResponse.html#method___construct"
        },                {
            "fqsen": "\\App\\EntryLocal\\ServiceResponse\u003A\u003A\u0024message",
            "name": "message",
            "summary": "",
            "url": "classes/App-EntryLocal-ServiceResponse.html#property_message"
        },                {
            "fqsen": "\\App\\EntryLocal\\ServiceResponseError",
            "name": "ServiceResponseError",
            "summary": "Error\u0020response\u0020properties\u0020class",
            "url": "classes/App-EntryLocal-ServiceResponseError.html"
        },                {
            "fqsen": "\\App\\EntryLocal\\ServiceResponseError\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-EntryLocal-ServiceResponseError.html#method___construct"
        },                {
            "fqsen": "\\App\\EntryLocal\\ServiceResponseError\u003A\u003A\u0024error",
            "name": "error",
            "summary": "",
            "url": "classes/App-EntryLocal-ServiceResponseError.html#property_error"
        },                {
            "fqsen": "\\App\\Exceptions\\ApprovalRequestException",
            "name": "ApprovalRequestException",
            "summary": "Exception\u0020if\u0020errors\u0020are\u0020returned\u0020when\u0020requesting\u0020approval\u0020for\u0020a\u0020ticket\u0020order",
            "url": "classes/App-Exceptions-ApprovalRequestException.html"
        },                {
            "fqsen": "\\App\\Exceptions\\ApprovalRequestExceptionInterface",
            "name": "ApprovalRequestExceptionInterface",
            "summary": "",
            "url": "classes/App-Exceptions-ApprovalRequestExceptionInterface.html"
        },                {
            "fqsen": "\\App\\Kernel",
            "name": "Kernel",
            "summary": "",
            "url": "classes/App-Kernel.html"
        },                {
            "fqsen": "\\App\\Model\\BarcodeGenerator",
            "name": "BarcodeGenerator",
            "summary": "",
            "url": "classes/App-Model-BarcodeGenerator.html"
        },                {
            "fqsen": "\\App\\Model\\BarcodeGenerator\u003A\u003AgenerateCode\u0028\u0029",
            "name": "generateCode",
            "summary": "Barcode\u0020generation\u0020method",
            "url": "classes/App-Model-BarcodeGenerator.html#method_generateCode"
        },                {
            "fqsen": "\\App\\Model\\BarcodeGenerator\u003A\u003AconvertHexSymbolsToNumber\u0028\u0029",
            "name": "convertHexSymbolsToNumber",
            "summary": "",
            "url": "classes/App-Model-BarcodeGenerator.html#method_convertHexSymbolsToNumber"
        },                {
            "fqsen": "\\App\\Model\\BarcodeGeneratorInterface",
            "name": "BarcodeGeneratorInterface",
            "summary": "Generates\u0020a\u0020barcode",
            "url": "classes/App-Model-BarcodeGeneratorInterface.html"
        },                {
            "fqsen": "\\App\\Model\\BarcodeGeneratorInterface\u003A\u003AgenerateCode\u0028\u0029",
            "name": "generateCode",
            "summary": "Barcode\u0020generation\u0020method",
            "url": "classes/App-Model-BarcodeGeneratorInterface.html#method_generateCode"
        },                {
            "fqsen": "\\App\\Model\\ResponseFormat",
            "name": "ResponseFormat",
            "summary": "Defines\u0020the\u0020format\u0020of\u0020returned\u0020messages",
            "url": "classes/App-Model-ResponseFormat.html"
        },                {
            "fqsen": "\\App\\Model\\ResponseFormat\u003A\u003AconvertArrayToObject\u0028\u0029",
            "name": "convertArrayToObject",
            "summary": "Generates\u0020a\u0020suitable\u0020object\u0020based\u0020on\u0020the\u0020received\u0020message\u0020data",
            "url": "classes/App-Model-ResponseFormat.html#method_convertArrayToObject"
        },                {
            "fqsen": "\\App\\Model\\TicketOrderModel",
            "name": "TicketOrderModel",
            "summary": "",
            "url": "classes/App-Model-TicketOrderModel.html"
        },                {
            "fqsen": "\\App\\Model\\TicketOrderModel\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Model-TicketOrderModel.html#method___construct"
        },                {
            "fqsen": "\\App\\Model\\TicketOrderModel\u003A\u003AaddOrderAndBook\u0028\u0029",
            "name": "addOrderAndBook",
            "summary": "Adds\u0020a\u0020new\u0020order\u0020and\u0020books\u0020tickets",
            "url": "classes/App-Model-TicketOrderModel.html#method_addOrderAndBook"
        },                {
            "fqsen": "\\App\\Model\\TicketOrderModel\u003A\u003AinitOrderReservation\u0028\u0029",
            "name": "initOrderReservation",
            "summary": "",
            "url": "classes/App-Model-TicketOrderModel.html#method_initOrderReservation"
        },                {
            "fqsen": "\\App\\Model\\TicketOrderModel\u003A\u003AinitOrder\u0028\u0029",
            "name": "initOrder",
            "summary": "",
            "url": "classes/App-Model-TicketOrderModel.html#method_initOrder"
        },                {
            "fqsen": "\\App\\Model\\TicketOrderModel\u003A\u003AgenerateBarcode\u0028\u0029",
            "name": "generateBarcode",
            "summary": "",
            "url": "classes/App-Model-TicketOrderModel.html#method_generateBarcode"
        },                {
            "fqsen": "\\App\\Model\\TicketOrderModel\u003A\u003AgenerateSalt\u0028\u0029",
            "name": "generateSalt",
            "summary": "",
            "url": "classes/App-Model-TicketOrderModel.html#method_generateSalt"
        },                {
            "fqsen": "\\App\\Model\\TicketOrderModel\u003A\u003AcheckBarcode\u0028\u0029",
            "name": "checkBarcode",
            "summary": "",
            "url": "classes/App-Model-TicketOrderModel.html#method_checkBarcode"
        },                {
            "fqsen": "\\App\\Model\\TicketOrderModel\u003A\u003AsaveBarcodeInMemory\u0028\u0029",
            "name": "saveBarcodeInMemory",
            "summary": "",
            "url": "classes/App-Model-TicketOrderModel.html#method_saveBarcodeInMemory"
        },                {
            "fqsen": "\\App\\Model\\TicketOrderModel\u003A\u003AremoveBarcodeInMemory\u0028\u0029",
            "name": "removeBarcodeInMemory",
            "summary": "",
            "url": "classes/App-Model-TicketOrderModel.html#method_removeBarcodeInMemory"
        },                {
            "fqsen": "\\App\\Model\\TicketOrderModel\u003A\u003AreserveAnOrder\u0028\u0029",
            "name": "reserveAnOrder",
            "summary": "",
            "url": "classes/App-Model-TicketOrderModel.html#method_reserveAnOrder"
        },                {
            "fqsen": "\\App\\Model\\TicketOrderModel\u003A\u003AapproveOrder\u0028\u0029",
            "name": "approveOrder",
            "summary": "",
            "url": "classes/App-Model-TicketOrderModel.html#method_approveOrder"
        },                {
            "fqsen": "\\App\\Model\\TicketOrderModel\u003A\u003AsaveOrder\u0028\u0029",
            "name": "saveOrder",
            "summary": "",
            "url": "classes/App-Model-TicketOrderModel.html#method_saveOrder"
        },                {
            "fqsen": "\\App\\Model\\TicketOrderModel\u003A\u003A\u0024barcodeGenerator",
            "name": "barcodeGenerator",
            "summary": "",
            "url": "classes/App-Model-TicketOrderModel.html#property_barcodeGenerator"
        },                {
            "fqsen": "\\App\\Model\\TicketOrderModel\u003A\u003A\u0024repo",
            "name": "repo",
            "summary": "",
            "url": "classes/App-Model-TicketOrderModel.html#property_repo"
        },                {
            "fqsen": "\\App\\Model\\TicketOrderModel\u003A\u003A\u0024repoBarcode",
            "name": "repoBarcode",
            "summary": "",
            "url": "classes/App-Model-TicketOrderModel.html#property_repoBarcode"
        },                {
            "fqsen": "\\App\\Model\\TicketOrderModel\u003A\u003A\u0024repoReservation",
            "name": "repoReservation",
            "summary": "",
            "url": "classes/App-Model-TicketOrderModel.html#property_repoReservation"
        },                {
            "fqsen": "\\App\\Model\\TicketOrderModel\u003A\u003A\u0024repoApprovalOrder",
            "name": "repoApprovalOrder",
            "summary": "",
            "url": "classes/App-Model-TicketOrderModel.html#property_repoApprovalOrder"
        },                {
            "fqsen": "\\App\\Model\\TicketOrderModelInterface",
            "name": "TicketOrderModelInterface",
            "summary": "Business\u0020logic\u0020for\u0020ticket\u0020order\u0020data.",
            "url": "classes/App-Model-TicketOrderModelInterface.html"
        },                {
            "fqsen": "\\App\\Model\\TicketOrderModelInterface\u003A\u003AaddOrderAndBook\u0028\u0029",
            "name": "addOrderAndBook",
            "summary": "Adds\u0020a\u0020new\u0020order\u0020and\u0020books\u0020tickets",
            "url": "classes/App-Model-TicketOrderModelInterface.html#method_addOrderAndBook"
        },                {
            "fqsen": "\\App\\Repository\\ApprovalOrdersRepository",
            "name": "ApprovalOrdersRepository",
            "summary": "",
            "url": "classes/App-Repository-ApprovalOrdersRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\ApprovalOrdersRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Repository-ApprovalOrdersRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Repository\\ApprovalOrdersRepository\u003A\u003ArequestApprovalOrder\u0028\u0029",
            "name": "requestApprovalOrder",
            "summary": "Makes\u0020a\u0020request\u0020to\u0020a\u0020third\u0020party\u0020service\u0020and\u0020requests\u0020order\u0020approval\nRequests\u0020order\u0020confirmation",
            "url": "classes/App-Repository-ApprovalOrdersRepository.html#method_requestApprovalOrder"
        },                {
            "fqsen": "\\App\\Repository\\ApprovalOrdersRepository\u003A\u003A\u0024client",
            "name": "client",
            "summary": "",
            "url": "classes/App-Repository-ApprovalOrdersRepository.html#property_client"
        },                {
            "fqsen": "\\App\\Repository\\ApprovalOrdersRepository\u003A\u003A\u0024config",
            "name": "config",
            "summary": "",
            "url": "classes/App-Repository-ApprovalOrdersRepository.html#property_config"
        },                {
            "fqsen": "\\App\\Repository\\ApprovalOrdersRepository\u003A\u003A\u0024responseFormat",
            "name": "responseFormat",
            "summary": "",
            "url": "classes/App-Repository-ApprovalOrdersRepository.html#property_responseFormat"
        },                {
            "fqsen": "\\App\\Repository\\ApprovalOrdersRepositoryInterface",
            "name": "ApprovalOrdersRepositoryInterface",
            "summary": "Repository\u0020for\u0020connecting\u0020to\u0020the\u0020approval\u0020service",
            "url": "classes/App-Repository-ApprovalOrdersRepositoryInterface.html"
        },                {
            "fqsen": "\\App\\Repository\\ApprovalOrdersRepositoryInterface\u003A\u003ArequestApprovalOrder\u0028\u0029",
            "name": "requestApprovalOrder",
            "summary": "Makes\u0020a\u0020request\u0020to\u0020a\u0020third\u0020party\u0020service\u0020and\u0020requests\u0020order\u0020approval\nRequests\u0020order\u0020confirmation",
            "url": "classes/App-Repository-ApprovalOrdersRepositoryInterface.html#method_requestApprovalOrder"
        },                {
            "fqsen": "\\App\\Repository\\BarcodeMemoryRepository",
            "name": "BarcodeMemoryRepository",
            "summary": "",
            "url": "classes/App-Repository-BarcodeMemoryRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\BarcodeMemoryRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Repository-BarcodeMemoryRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Repository\\BarcodeMemoryRepository\u003A\u003AhasBarcode\u0028\u0029",
            "name": "hasBarcode",
            "summary": "Checks\u0020whether\u0020a\u0020barcode\u0020is\u0020in\u0020memory\u0020\u0028\u0438\u0433\u0430\u0430\u0443\u043A\u0029",
            "url": "classes/App-Repository-BarcodeMemoryRepository.html#method_hasBarcode"
        },                {
            "fqsen": "\\App\\Repository\\BarcodeMemoryRepository\u003A\u003AsaveBarcode\u0028\u0029",
            "name": "saveBarcode",
            "summary": "Saves\u0020the\u0020barcode\u0020to\u0020memory\u0020\u0028buffer\u0029",
            "url": "classes/App-Repository-BarcodeMemoryRepository.html#method_saveBarcode"
        },                {
            "fqsen": "\\App\\Repository\\BarcodeMemoryRepository\u003A\u003AremoveBarcode\u0028\u0029",
            "name": "removeBarcode",
            "summary": "Deletes\u0020a\u0020barcode\u0020from\u0020memory\u0020\u0028buffer\u0029",
            "url": "classes/App-Repository-BarcodeMemoryRepository.html#method_removeBarcode"
        },                {
            "fqsen": "\\App\\Repository\\BarcodeMemoryRepository\u003A\u003AgetEntity\u0028\u0029",
            "name": "getEntity",
            "summary": "",
            "url": "classes/App-Repository-BarcodeMemoryRepository.html#method_getEntity"
        },                {
            "fqsen": "\\App\\Repository\\BarcodeMemoryRepository\u003A\u003A\u0024entityManager",
            "name": "entityManager",
            "summary": "",
            "url": "classes/App-Repository-BarcodeMemoryRepository.html#property_entityManager"
        },                {
            "fqsen": "\\App\\Repository\\BarcodeMemoryRepositoryInterface",
            "name": "BarcodeMemoryRepositoryInterface",
            "summary": "Intended\u0020as\u0020a\u0020buffer\u0020for\u0020a\u0020barcode\u0020to\u0020determine\u0020between\u0020requests\u0020that\u0020a\u0020name\u0020is\u0020temporarily\u0020reserved.",
            "url": "classes/App-Repository-BarcodeMemoryRepositoryInterface.html"
        },                {
            "fqsen": "\\App\\Repository\\BarcodeMemoryRepositoryInterface\u003A\u003AhasBarcode\u0028\u0029",
            "name": "hasBarcode",
            "summary": "Checks\u0020whether\u0020a\u0020barcode\u0020is\u0020in\u0020memory\u0020\u0028\u0438\u0433\u0430\u0430\u0443\u043A\u0029",
            "url": "classes/App-Repository-BarcodeMemoryRepositoryInterface.html#method_hasBarcode"
        },                {
            "fqsen": "\\App\\Repository\\BarcodeMemoryRepositoryInterface\u003A\u003AsaveBarcode\u0028\u0029",
            "name": "saveBarcode",
            "summary": "Saves\u0020the\u0020barcode\u0020to\u0020memory\u0020\u0028buffer\u0029",
            "url": "classes/App-Repository-BarcodeMemoryRepositoryInterface.html#method_saveBarcode"
        },                {
            "fqsen": "\\App\\Repository\\BarcodeMemoryRepositoryInterface\u003A\u003AremoveBarcode\u0028\u0029",
            "name": "removeBarcode",
            "summary": "Deletes\u0020a\u0020barcode\u0020from\u0020memory\u0020\u0028buffer\u0029",
            "url": "classes/App-Repository-BarcodeMemoryRepositoryInterface.html#method_removeBarcode"
        },                {
            "fqsen": "\\App\\Repository\\ReservationOrderRepository",
            "name": "ReservationOrderRepository",
            "summary": "",
            "url": "classes/App-Repository-ReservationOrderRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\ReservationOrderRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Repository-ReservationOrderRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Repository\\ReservationOrderRepository\u003A\u003AcreateReservation\u0028\u0029",
            "name": "createReservation",
            "summary": "Creates\u0020an\u0020order\u0020reservation",
            "url": "classes/App-Repository-ReservationOrderRepository.html#method_createReservation"
        },                {
            "fqsen": "\\App\\Repository\\ReservationOrderRepository\u003A\u003A\u0024client",
            "name": "client",
            "summary": "",
            "url": "classes/App-Repository-ReservationOrderRepository.html#property_client"
        },                {
            "fqsen": "\\App\\Repository\\ReservationOrderRepository\u003A\u003A\u0024config",
            "name": "config",
            "summary": "",
            "url": "classes/App-Repository-ReservationOrderRepository.html#property_config"
        },                {
            "fqsen": "\\App\\Repository\\ReservationOrderRepository\u003A\u003A\u0024responseFormat",
            "name": "responseFormat",
            "summary": "",
            "url": "classes/App-Repository-ReservationOrderRepository.html#property_responseFormat"
        },                {
            "fqsen": "\\App\\Repository\\ReservationOrderRepositoryInterface",
            "name": "ReservationOrderRepositoryInterface",
            "summary": "Repository\u0020for\u0020connecting\u0020to\u0020the\u0020reservation\u0020service",
            "url": "classes/App-Repository-ReservationOrderRepositoryInterface.html"
        },                {
            "fqsen": "\\App\\Repository\\ReservationOrderRepositoryInterface\u003A\u003AcreateReservation\u0028\u0029",
            "name": "createReservation",
            "summary": "Creates\u0020an\u0020order\u0020reservation",
            "url": "classes/App-Repository-ReservationOrderRepositoryInterface.html#method_createReservation"
        },                {
            "fqsen": "\\App\\Repository\\TicketOrderRepository",
            "name": "TicketOrderRepository",
            "summary": "",
            "url": "classes/App-Repository-TicketOrderRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\TicketOrderRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Repository-TicketOrderRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Repository\\TicketOrderRepository\u003A\u003AsaveOrder\u0028\u0029",
            "name": "saveOrder",
            "summary": "Add\u0020Ticket\u0020Order\u0020in\u0020DB",
            "url": "classes/App-Repository-TicketOrderRepository.html#method_saveOrder"
        },                {
            "fqsen": "\\App\\Repository\\TicketOrderRepository\u003A\u003AhasOrderByBarcode\u0028\u0029",
            "name": "hasOrderByBarcode",
            "summary": "Checks\u0020the\u0020presence\u0020of\u0020an\u0020order\u0020using\u0020a\u0020barcode",
            "url": "classes/App-Repository-TicketOrderRepository.html#method_hasOrderByBarcode"
        },                {
            "fqsen": "\\App\\Repository\\TicketOrderRepository\u003A\u003A\u0024entityManager",
            "name": "entityManager",
            "summary": "",
            "url": "classes/App-Repository-TicketOrderRepository.html#property_entityManager"
        },                {
            "fqsen": "\\App\\Repository\\TicketOrderRepositoryInterface",
            "name": "TicketOrderRepositoryInterface",
            "summary": "The\u0020repository\u0020is\u0020responsible\u0020for\u0020managing\u0020ticket\u0020order\u0020data.",
            "url": "classes/App-Repository-TicketOrderRepositoryInterface.html"
        },                {
            "fqsen": "\\App\\Repository\\TicketOrderRepositoryInterface\u003A\u003AsaveOrder\u0028\u0029",
            "name": "saveOrder",
            "summary": "Add\u0020Ticket\u0020Order\u0020in\u0020DB",
            "url": "classes/App-Repository-TicketOrderRepositoryInterface.html#method_saveOrder"
        },                {
            "fqsen": "\\App\\Repository\\TicketOrderRepositoryInterface\u003A\u003AhasOrderByBarcode\u0028\u0029",
            "name": "hasOrderByBarcode",
            "summary": "Checks\u0020the\u0020presence\u0020of\u0020an\u0020order\u0020using\u0020a\u0020barcode",
            "url": "classes/App-Repository-TicketOrderRepositoryInterface.html#method_hasOrderByBarcode"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\App\\Controller",
            "name": "Controller",
            "summary": "",
            "url": "namespaces/app-controller.html"
        },                {
            "fqsen": "\\App\\Entity",
            "name": "Entity",
            "summary": "",
            "url": "namespaces/app-entity.html"
        },                {
            "fqsen": "\\App\\EntryLocal",
            "name": "EntryLocal",
            "summary": "",
            "url": "namespaces/app-entrylocal.html"
        },                {
            "fqsen": "\\App\\Exceptions",
            "name": "Exceptions",
            "summary": "",
            "url": "namespaces/app-exceptions.html"
        },                {
            "fqsen": "\\App",
            "name": "App",
            "summary": "",
            "url": "namespaces/app.html"
        },                {
            "fqsen": "\\App\\Model",
            "name": "Model",
            "summary": "",
            "url": "namespaces/app-model.html"
        },                {
            "fqsen": "\\App\\Repository",
            "name": "Repository",
            "summary": "",
            "url": "namespaces/app-repository.html"
        }            ]
);
